<style>
    /* The MIT License */
    .dropzone,
    .dropzone *,
    .dropzone-previews,
    .dropzone-previews * {
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
    }
    .dropzone {
        position: relative;
        border: 1px solid rgba(0,0,0,0.08);
        background: rgba(0,0,0,0.02);
        padding: 1em;
    }
    .dropzone.dz-clickable {
        cursor: pointer;
    }
    .dropzone.dz-clickable .dz-message,
    .dropzone.dz-clickable .dz-message span {
        cursor: pointer;
    }
    .dropzone.dz-clickable * {
        cursor: default;
    }
    .dropzone .dz-message {
        opacity: 1;
        -ms-filter: none;
        filter: none;
    }
    .dropzone.dz-drag-hover {
        border-color: rgba(0,0,0,0.15);
        background: rgba(0,0,0,0.04);
    }
    .dropzone.dz-started .dz-message {
        display: none;
    }
    .dropzone .dz-preview,
    .dropzone-previews .dz-preview {
        background: rgba(255,255,255,0.8);
        position: relative;
        display: inline-block;
        margin: 17px;
        vertical-align: top;
        border: 1px solid #acacac;
        padding: 6px 6px 6px 6px;
    }
    .dropzone .dz-preview.dz-file-preview [data-dz-thumbnail],
    .dropzone-previews .dz-preview.dz-file-preview [data-dz-thumbnail] {
        display: none;
    }
    .dropzone .dz-preview .dz-details,
    .dropzone-previews .dz-preview .dz-details {
        width: 100px;
        height: 100px;
        position: relative;
        background: #ebebeb;
        padding: 5px;
        margin-bottom: 22px;
    }
    .dropzone .dz-preview .dz-details .dz-filename,
    .dropzone-previews .dz-preview .dz-details .dz-filename {
        overflow: hidden;
        height: 100%;
    }
    .dropzone .dz-preview .dz-details img,
    .dropzone-previews .dz-preview .dz-details img {
        position: absolute;
        top: 0;
        left: 0;
        width: 100px;
        height: 100px;
    }
    .dropzone .dz-preview .dz-details .dz-size,
    .dropzone-previews .dz-preview .dz-details .dz-size {
        position: absolute;
        bottom: -28px;
        left: 3px;
        height: 28px;
        line-height: 28px;
    }
    .dropzone .dz-preview.dz-error .dz-error-mark,
    .dropzone-previews .dz-preview.dz-error .dz-error-mark {
        display: block;
    }
    .dropzone .dz-preview.dz-success .dz-success-mark,
    .dropzone-previews .dz-preview.dz-success .dz-success-mark {
        display: block;
    }
    .dropzone .dz-preview:hover .dz-details img,
    .dropzone-previews .dz-preview:hover .dz-details img {
        display: none;
    }
    .dropzone .dz-preview .dz-success-mark,
    .dropzone-previews .dz-preview .dz-success-mark,
    .dropzone .dz-preview .dz-error-mark,
    .dropzone-previews .dz-preview .dz-error-mark {
        display: none;
        position: absolute;
        width: 40px;
        height: 40px;
        font-size: 30px;
        text-align: center;
        right: -10px;
        top: -10px;
    }
    .dropzone .dz-preview .dz-success-mark,
    .dropzone-previews .dz-preview .dz-success-mark {
        color: #8cc657;
    }
    .dropzone .dz-preview .dz-error-mark,
    .dropzone-previews .dz-preview .dz-error-mark {
        color: #ee162d;
    }
    .dropzone .dz-preview .dz-progress,
    .dropzone-previews .dz-preview .dz-progress {
        position: absolute;
        top: 100px;
        left: 6px;
        right: 6px;
        height: 6px;
        background: #d7d7d7;
        display: none;
    }
    .dropzone .dz-preview .dz-progress .dz-upload,
    .dropzone-previews .dz-preview .dz-progress .dz-upload {
        display: block;
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        width: 0%;
        background-color: #8cc657;
    }
    .dropzone .dz-preview.dz-processing .dz-progress,
    .dropzone-previews .dz-preview.dz-processing .dz-progress {
        display: block;
    }
    .dropzone .dz-preview .dz-error-message,
    .dropzone-previews .dz-preview .dz-error-message {
        display: none;
        position: absolute;
        top: -5px;
        left: -20px;
        background: rgba(245,245,245,0.8);
        padding: 8px 10px;
        color: #800;
        min-width: 140px;
        max-width: 500px;
        z-index: 500;
    }
    .dropzone .dz-preview:hover.dz-error .dz-error-message,
    .dropzone-previews .dz-preview:hover.dz-error .dz-error-message {
        display: block;
    }
    .dropzone {
        border: 1px solid rgba(0,0,0,0.03);
        min-height: 360px;
        -webkit-border-radius: 3px;
        border-radius: 3px;
        background: rgba(0,0,0,0.03);
        padding: 23px;
    }
    .dropzone .dz-default.dz-message {
        opacity: 1;
        -ms-filter: none;
        filter: none;
        -webkit-transition: opacity 0.3s ease-in-out;
        -moz-transition: opacity 0.3s ease-in-out;
        -o-transition: opacity 0.3s ease-in-out;
        -ms-transition: opacity 0.3s ease-in-out;
        transition: opacity 0.3s ease-in-out;
        background-image: url("../images/spritemap.png");
        background-repeat: no-repeat;
        background-position: 0 0;
        position: absolute;
        width: 428px;
        height: 123px;
        margin-left: -214px;
        margin-top: -61.5px;
        top: 50%;
        left: 50%;
    }
    @media all and (-webkit-min-device-pixel-ratio:1.5),(min--moz-device-pixel-ratio:1.5),(-o-min-device-pixel-ratio:1.5/1),(min-device-pixel-ratio:1.5),(min-resolution:138dpi),(min-resolution:1.5dppx) {
        .dropzone .dz-default.dz-message {
            background-image: url("../images/spritemap@2x.png");
            -webkit-background-size: 428px 406px;
            -moz-background-size: 428px 406px;
            background-size: 428px 406px;
        }
    }
    .dropzone .dz-default.dz-message span {
        display: none;
    }
    .dropzone.dz-square .dz-default.dz-message {
        background-position: 0 -123px;
        width: 268px;
        margin-left: -134px;
        height: 174px;
        margin-top: -87px;
    }
    .dropzone.dz-drag-hover .dz-message {
        opacity: 0.15;
        -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=15)";
        filter: alpha(opacity=15);
    }
    .dropzone.dz-started .dz-message {
        display: block;
        opacity: 0;
        -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
        filter: alpha(opacity=0);
    }
    .dropzone .dz-preview,
    .dropzone-previews .dz-preview {
        -webkit-box-shadow: 1px 1px 4px rgba(0,0,0,0.16);
        box-shadow: 1px 1px 4px rgba(0,0,0,0.16);
        font-size: 14px;
    }
    .dropzone .dz-preview.dz-image-preview:hover .dz-details img,
    .dropzone-previews .dz-preview.dz-image-preview:hover .dz-details img {
        display: block;
        opacity: 0.1;
        -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=10)";
        filter: alpha(opacity=10);
    }
    .dropzone .dz-preview.dz-success .dz-success-mark,
    .dropzone-previews .dz-preview.dz-success .dz-success-mark {
        opacity: 1;
        -ms-filter: none;
        filter: none;
    }
    .dropzone .dz-preview.dz-error .dz-error-mark,
    .dropzone-previews .dz-preview.dz-error .dz-error-mark {
        opacity: 1;
        -ms-filter: none;
        filter: none;
    }
    .dropzone .dz-preview.dz-error .dz-progress .dz-upload,
    .dropzone-previews .dz-preview.dz-error .dz-progress .dz-upload {
        background: #ee1e2d;
    }
    .dropzone .dz-preview .dz-error-mark,
    .dropzone-previews .dz-preview .dz-error-mark,
    .dropzone .dz-preview .dz-success-mark,
    .dropzone-previews .dz-preview .dz-success-mark {
        display: block;
        opacity: 0;
        -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
        filter: alpha(opacity=0);
        -webkit-transition: opacity 0.4s ease-in-out;
        -moz-transition: opacity 0.4s ease-in-out;
        -o-transition: opacity 0.4s ease-in-out;
        -ms-transition: opacity 0.4s ease-in-out;
        transition: opacity 0.4s ease-in-out;
        background-image: url("../images/spritemap.png");
        background-repeat: no-repeat;
    }
    @media all and (-webkit-min-device-pixel-ratio:1.5),(min--moz-device-pixel-ratio:1.5),(-o-min-device-pixel-ratio:1.5/1),(min-device-pixel-ratio:1.5),(min-resolution:138dpi),(min-resolution:1.5dppx) {
        .dropzone .dz-preview .dz-error-mark,
        .dropzone-previews .dz-preview .dz-error-mark,
        .dropzone .dz-preview .dz-success-mark,
        .dropzone-previews .dz-preview .dz-success-mark {
            background-image: url("../images/spritemap@2x.png");
            -webkit-background-size: 428px 406px;
            -moz-background-size: 428px 406px;
            background-size: 428px 406px;
        }
    }
    .dropzone .dz-preview .dz-error-mark span,
    .dropzone-previews .dz-preview .dz-error-mark span,
    .dropzone .dz-preview .dz-success-mark span,
    .dropzone-previews .dz-preview .dz-success-mark span {
        display: none;
    }
    .dropzone .dz-preview .dz-error-mark,
    .dropzone-previews .dz-preview .dz-error-mark {
        background-position: -268px -123px;
    }
    .dropzone .dz-preview .dz-success-mark,
    .dropzone-previews .dz-preview .dz-success-mark {
        background-position: -268px -163px;
    }
    .dropzone .dz-preview .dz-progress .dz-upload,
    .dropzone-previews .dz-preview .dz-progress .dz-upload {
        -webkit-animation: loading 0.4s linear infinite;
        -moz-animation: loading 0.4s linear infinite;
        -o-animation: loading 0.4s linear infinite;
        -ms-animation: loading 0.4s linear infinite;
        animation: loading 0.4s linear infinite;
        -webkit-transition: width 0.3s ease-in-out;
        -moz-transition: width 0.3s ease-in-out;
        -o-transition: width 0.3s ease-in-out;
        -ms-transition: width 0.3s ease-in-out;
        transition: width 0.3s ease-in-out;
        -webkit-border-radius: 2px;
        border-radius: 2px;
        position: absolute;
        top: 0;
        left: 0;
        width: 0%;
        height: 100%;
        background-image: url("../images/spritemap.png");
        background-repeat: repeat-x;
        background-position: 0px -400px;
    }
    @media all and (-webkit-min-device-pixel-ratio:1.5),(min--moz-device-pixel-ratio:1.5),(-o-min-device-pixel-ratio:1.5/1),(min-device-pixel-ratio:1.5),(min-resolution:138dpi),(min-resolution:1.5dppx) {
        .dropzone .dz-preview .dz-progress .dz-upload,
        .dropzone-previews .dz-preview .dz-progress .dz-upload {
            background-image: url("../images/spritemap@2x.png");
            -webkit-background-size: 428px 406px;
            -moz-background-size: 428px 406px;
            background-size: 428px 406px;
        }
    }
    .dropzone .dz-preview.dz-success .dz-progress,
    .dropzone-previews .dz-preview.dz-success .dz-progress {
        display: block;
        opacity: 0;
        -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
        filter: alpha(opacity=0);
        -webkit-transition: opacity 0.4s ease-in-out;
        -moz-transition: opacity 0.4s ease-in-out;
        -o-transition: opacity 0.4s ease-in-out;
        -ms-transition: opacity 0.4s ease-in-out;
        transition: opacity 0.4s ease-in-out;
    }
    .dropzone .dz-preview .dz-error-message,
    .dropzone-previews .dz-preview .dz-error-message {
        display: block;
        opacity: 0;
        -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
        filter: alpha(opacity=0);
        -webkit-transition: opacity 0.3s ease-in-out;
        -moz-transition: opacity 0.3s ease-in-out;
        -o-transition: opacity 0.3s ease-in-out;
        -ms-transition: opacity 0.3s ease-in-out;
        transition: opacity 0.3s ease-in-out;
    }
    .dropzone .dz-preview:hover.dz-error .dz-error-message,
    .dropzone-previews .dz-preview:hover.dz-error .dz-error-message {
        opacity: 1;
        -ms-filter: none;
        filter: none;
    }
    .dropzone a.dz-remove,
    .dropzone-previews a.dz-remove {
        background-image: -webkit-linear-gradient(top, #fafafa, #eee);
        background-image: -moz-linear-gradient(top, #fafafa, #eee);
        background-image: -o-linear-gradient(top, #fafafa, #eee);
        background-image: -ms-linear-gradient(top, #fafafa, #eee);
        background-image: linear-gradient(to bottom, #fafafa, #eee);
        -webkit-border-radius: 2px;
        border-radius: 2px;
        border: 1px solid #eee;
        text-decoration: none;
        display: block;
        padding: 4px 5px;
        text-align: center;
        color: #aaa;
        margin-top: 26px;
    }
    .dropzone a.dz-remove:hover,
    .dropzone-previews a.dz-remove:hover {
        color: #666;
    }
    @-moz-keyframes loading {
        from {
            background-position: 0 -400px;
        }
        to {
            background-position: -7px -400px;
        }
    }
    @-webkit-keyframes loading {
        from {
            background-position: 0 -400px;
        }
        to {
            background-position: -7px -400px;
        }
    }
    @-o-keyframes loading {
        from {
            background-position: 0 -400px;
        }
        to {
            background-position: -7px -400px;
        }
    }
    @keyframes loading {
        from {
            background-position: 0 -400px;
        }
        to {
            background-position: -7px -400px;
        }
    }
</style>
<div class="row">
    <div class="col-lg-3">
        <?php if (!empty($this->types)): ?>
            <h2><?= $this->translate('Card') ?></h2>
            <form name="setup" method="POST" action="/heybro/heybro/save">
                <label><?= $this->translate('Select type') ?></label>
                <br>
                <select name="type">
                    <option value="0"><?= $this->translate('Select type') ?></option>
                    <?php foreach ($this->types as $type): ?>
                        <option value="<?= $type['id'] ?>" <?= ($this->config['type'] == $type['id']) ? 'selected' : '' ?>><?= $type['name'] ?></option>
                    <?php endforeach; ?>
                </select>
                <br><br> 
                <div id="input_fields">
                    <label><?= $this->translate('Add character') ?></label>
                    <br>
                    <input type="text" value="" name="character[]">
                    <br>
                    <?php if (!empty($this->config['character'])): ?>
                        <?php foreach ($this->config['character'] as $character): ?>
                            <input type="text" value="<?= $character ?>" name="character[]">
                            <br>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
                <div id="add-field">
                    <i class="fa fa-plus-square-o" aria-hidden="true"></i>
                </div>
                <button type="submit" class="btn btn-primary"><?= $this->translate('Save') ?></button>
            </form>
        <?php endif; ?>
    </div>
    <div class="col-lg-3">
        <h2><?= $this->translate('Products') ?></h2>
        <form id="filter" method="POST" action="/heybro/heybro/save-product" name="heybro-product" class="form-group">
            <h3><?= $this->translate('Toy') ?></h3>
            <input type="text" class="search animal" name="search[animal]">
            <input type="button" id="animal" name="search" value="<?= $this->translate('Search') ?>" class="btn btn-primary">
            <div class="animal" >
                <?php if (!empty($this->animal)): ?>
                    <?php foreach ($this->animal as $animal): ?>
                        <div>                                    
                            <input type="checkbox" class="animal" value="<?= $animal['product_id'] ?>" name="animal[<?= $animal['product_name'] ?>]" checked="true"><label for="animal"><?= $animal['product_name'] ?></label>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <h3><?= $this->translate('Jacket') ?></h3>
            <input type="text" class="search topic" name="search[top]">
            <input type="button" id="topic" name="search" value="<?= $this->translate('Search') ?>" class="btn btn-primary">
            <div class="topic" >
                <?php if (!empty($this->topic)): ?>
                    <?php foreach ($this->topic as $top): ?>
                        <div>                                    
                            <input type="checkbox" class="topic" value="<?= $top['product_id'] ?>" name="topic[<?= $top['product_name'] ?>]" checked="true"><label for="topic"><?= $top['product_name'] ?></label>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <h3><?= $this->translate('Trousers') ?></h3>
            <input type="text" class="search pants" name="search[pants]">
            <input type="button" id="pants" name="search" value="<?= $this->translate('Search') ?>" class="btn btn-primary">
            <div class="pants" >
                <?php if (!empty($this->pants)): ?>
                    <?php foreach ($this->pants as $pants): ?>
                        <div>                                    
                            <input type="checkbox" class="pants" value="<?= $pants['product_id'] ?>" name="pants[<?= $pants['product_name'] ?>]" checked="true"><label for="top"><?= $pants['product_name'] ?></label>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <button type="submit" class="btn btn-primary"><?= $this->translate('Save') ?></button>
        </form>
    </div>
    <div class="col-lg-3">
        <h2><?= $this->translate('Foto upload') ?></h2>
        <h3><?= $this->translate('Toy') ?></h3>
        <select name="toy">
            <option value="0"><?= $this->translate('Select value') ?></option>
            <?php if (!empty($this->animal)): ?>
                <?php foreach ($this->animal as $value): ?>
                    <option value="<?= $value['product_id'] ?>"><?= $value['product_name'] ?></option>
                <?php endforeach; ?>
            <?php endif; ?>
        </select>
        <h3><?= $this->translate('Jacket') ?></h3>
        <select name="topic">
            <option value="0"><?= $this->translate('Select value') ?></option>
            <?php if (!empty($this->topic)): ?>
                <?php foreach ($this->topic as $value): ?>
                    <option value="<?= $value['product_id'] ?>"><?= $value['product_name'] ?></option>
                <?php endforeach; ?>
            <?php endif; ?>
        </select>
        <h3><?= $this->translate('Trousers') ?></h3>
        <select name="pants">
            <option value="0"><?= $this->translate('Select value') ?></option>
            <?php if (!empty($this->pants)): ?>
                <?php foreach ($this->pants as $value): ?>
                    <option value="<?= $value['product_id'] ?>"><?= $value['product_name'] ?></option>
                <?php endforeach; ?>
            <?php endif; ?>
        </select>
    </div>    
    <div class="col-lg-3" style="text-align: center; ">
        <form action="/heybro/heybro/upload" class="dropzone" id="dropzone">
            <h3><?= $this->translate('Drop files here to upload') ?></h3>
        </form>
    </div>
</div>   
<div class="row">
    <div class="col-lg-12">
        <?php if (!empty($this->data)): ?>
            <h2><?= $this->translate('Info') ?></h2>
            <table id="infoTable">
                <thead>
                    <tr>
                        <th><?= $this->translate('Code') ?></th>
                        <th><?= $this->translate('Username') ?></th>
                        <th><?= $this->translate('Product') ?></th>
                        <th><?= $this->translate('Order') ?></th>
                        <th><?= $this->translate('Date') ?></th>
                    </tr>
                </thead>
                <tbody>


                    <?php foreach ($this->data as $info): ?>
                        <tr>
                            <td><?= $info['code'] ?></td>
                            <td><a href="/contact/index/view/id/<?= $info['id'] ?>"><?= $info['name'] ?></a></td>
                            <td><a href="/shop/products/edit/id/<?= $info['product_id'] ?>"><?= $info['product_name'] ?></a></td>
                            <td><a href="/order/index/one/order_id/<?= $info['order_id'] ?>"><?= $info['order_id'] ?></a></td>
                            <td><?= $info['date'] ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

        <?php endif; ?>
    </div>
</div>


<script>
    $(document).ready(function () {
        $(function () {
            Dropzone.options.dropzone = {
                maxFilesize: 5,
                addRemoveLinks: false,
                dictResponseError: 'Server not Configured',
                acceptedFiles: "image/*",
                dictDefaultMessage: 'Перетащите файлы сюда для загрузки',
                init: function () {
                    var self = this;
                    // config
//                    self.options.addRemoveLinks = true;
//                    self.options.dictRemoveFile = "Delete";
//                    New file added
                    self.on("addedfile", function (file) {
                        console.log('new file added ', file);
                    });
                    // Send file starts
                    self.on("sending", function (file) {
                        var toy = $('select[name=toy]').val();
                        var topic = $('select[name=topic]').val();
                        var pants = $('select[name=pants]').val();
                        var data = {
                            toy: toy,
                            topic: topic,
                            pants: pants
                        }
                        $.ajax({
                            url: '/heybro/heybro/upload',
                            data: data,
                            type: 'POST'
                        });
                        self.options.params = data;
                        console.log(data);
                        $('.meter').show();
                    });

                    // File upload Progress
                    self.on("totaluploadprogress", function (progress) {
                        $('.roller').width(progress + '%');
                    });

                    self.on("queuecomplete", function (progress) {
                        $('.meter').delay(999).slideUp(999);
                    });

                    // On removing file
//                    self.on("removedfile", function (file) {
//                        console.log(file);
//                    });
                    self.on("complete", function (file) {
                        self.removeFile(file);
                    });
                }
            };
        })

        $('#infoTable').DataTable();
        $('#add-field').click(function () {
            $('#input_fields').append('<input type="text" value="" name="character[]"><br>');
        });

        $(':button[name=search]').click(function (e) {
            e.preventDefault();
            var id = $(this).attr('id');

            var search = $('.search').filter('.' + id).val();

            var checkbox = [];
            $(':checkbox.' + id).each(function () {
                checkbox.push($(this).attr('value'));
            });
            console.log(checkbox);
            $('div.' + id).empty();
            if (search.length > 0) {
                var data = {
                    id: id,
                    search: search,
                    checkbox: checkbox,
                }
                //                console.log(data);
                $.ajax({
                    url: '/heybro/heybro/search',
                    type: 'POST',
                    data: data,
                    success: function (responce) {
                        $('div.' + responce.id).append(responce.html);
                    }
                });
            }

        });

    });
</script>