<div class="title-left"><?= $this->title; ?></div>

<?php if ($this->no_variants == '0'): ?>
    <div class="check-field"><?= $this->translate('Enter at least 2 possible answers'); ?></div>
<?php endif; ?>
<div class="row">

    <div class="col-lg-12">
        <?php echo $this->form; ?>
    </div>
</div>


<script type="text/javascript">

    translation1 = <?= json_encode($this->translate('Delete variant')); ?>;
    translation2 = <?= json_encode($this->translate('Variants of answers')); ?>;
    translation3 = <?= json_encode($this->translate('Answer option')); ?>;
    translation4 = <?= json_encode($this->translate('There are variants of answers that are repeated')); ?>;

    $(document).ready(function () {



        var count_fields = $(".add-variant").attr('id').slice(12);

        if (count_fields > 2) {
            var count_del_button = 1;
        } else {
            var count_del_button = 3;

            for (j = 1; j < 3; j++) {
                $("#variant" + j + "-label").wrapAll('<div class="cell-no-border cells-no-border' + j + '" id="cell-no-border' + j + '"></div>');
                $("#variant" + j + "-element").wrapAll('<div class="cell-no-border cells-no-border' + j + '" id="cell-no-border' + j + '"></div>');

                $("#variant" + j + "-element").parent().after(new_del_button);

                var div_row = '<div class="row-no-border" id ="row-no-border' + j + '">'
                div_row += '</div>';

                $(".cells-no-border" + j).wrapAll(div_row);

                var div_table = '<div class="table-no-border" id ="table-no-border' + j + '">';
                div_table += '</div>';

                $("#row-no-border" + j).wrapAll(div_table);

                $('dd#variant' + j + '-element input').css('margin', '0 0 0 -44px');
            }

        }

        for (i = count_del_button; i <= count_fields; i++) {
            $("#variant" + i + "-label").wrapAll('<div class="cell-no-border cells-no-border' + i + '" id="cell-no-border' + i + '"></div>');
            $("#variant" + i + "-element").wrapAll('<div class="cell-no-border cells-no-border' + i + '" id="cell-no-border' + i + '"></div>');

            var new_del_button = '<div class="cell-no-border cells-no-border' + i + '" id="cell-no-border' + i + '">';
            new_del_button += '<a id="delete-variant-' + i + '" class="delete-variant" style="cursor: pointer;" title="' + translation1 + '"><i class="fa fa-times"></i></a>'
            new_del_button += '</div>';

            $("#variant" + i + "-element").parent().after(new_del_button);

            var div_row = '<div class="row-no-border" id ="row-no-border' + i + '">'
            div_row += '</div>';

            $(".cells-no-border" + i).wrapAll(div_row);

            var div_table = '<div class="table-no-border" id ="table-no-border' + i + '">';
            div_table += '</div>';

            $("#row-no-border" + i).wrapAll(div_table);

            $('dd#variant' + i + '-element input').attr('size', '43');
            if (i < 10) {
                $('dd#variant' + i + '-element input').css('margin', '0 0 0 -41px');
            } else if (i > 9 && i < 100) {
                $('dd#variant' + i + '-element input').css('margin', '0 0 0 -49px');
            } else if (i > 99) {
                $('dd#variant' + i + '-element input').css('margin', '0 0 0 -58px');
            }
        }

        $("#editable-element").after('<div class="title-left" style="margin:10px 0 5px 20px; font-size: 18px;">' + translation2 + ':</div>');

    })
</script>
